language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.6'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
after_script:
  - npm run remove-coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
  global:
    - 'MAJOR_VERSIONS=master,stage'
    - DEEP_NO_INTERACTION=1
    - E2E_TESTING=none
    - secure: 
        NIHVj4RBAHpPyLFXfZX6Cvo0xhF8b2cXEY10P/++w0Zc4P2QPX3i6jMCoP87beIBKerawB3hfb+6tM7/23eNjfYCkW3IBEnpSo3KhyZYSRM8JUmkOMB589/MeNfJQqLAJlUZ/NP/91yzRcNxOBB0dMBj5bU0XklmKBxEt9jeAhbq67HHI4pq653ms4fzOW0P4tRQcASKgRCB2zO4Vr5fBPHHmXdgd7KI/pEs1v1JhZbIAoiT3aoMzD4j8z5gKlCYASvsT2omT5kauxCGToYFb0nKZVsYsdchZvMWvLcry1ttfYIXsF0jrKnoqcWfSTShTppuudaq3Mx3hzYhUgeXGPlD1/+DXdtv23Vs68+QuBtqjfCgXVRKhvVVX4p8NprtFkU00tRrglktwnBf9j9k74SNKsrMeRNx8iV7J5Egpebc7ulYvxVbMgeFskTQGcorffG1cVsZnM6JOI2UQ2v83DkuSJK8YewJrB1veDS057zq2zqXEb4qfGA79grp4AIm7G2ZTLYm68lBKd1eP2KK9ovVcu3iMtu2g0wr8UE1bf9KscdPkZtB3HYlPdJS+4+7I65vm4zXJZ6cv1i3yyp8btWXw0zPwkZydTaHD2QjRsxTrSbJ+fNFZt43HfnBqLqsTQWkU+UFxmWkVL6ve8zEgCXKwzIUJWjOMeTFT85gZoY=
    - secure: 
        ehWQ1c4MRPUeomHUsiCFKGKbtt3YyFtLVSoinLBhcswBuFCwDyfus3jn9PssFnj64E2cwxyCDY6ZbukHpg6GrHTzbb+tfR+c4MHQnqJ3IRlgSt8eQ5DBFDHV3jcJvJvL9jN9nepGVVL6TAC0AMRIirr9xD5xIYa0Y1bmjEg7FGqnmtGybMW4LTVRXo2uMK8AJ2bUurRAS6wtxc7v9TwMRlFBNpr448H/kEUtxFowr/3qG334ON5v+9wwNVMu0f7ieXrmjPx6yGcEw6GFPbk75OIoqxg0zqODkWZBqRppy6nLZf35rs4h9RnJZWyBut9zuVS7JR1ekkkJJx3nLoVNrw5AMpB9mNBJpkr0AcFYway+KUveFpap9oQpQbY61/TntjC44pJhgWiTX9ZxDoDChG12OPz2Y1Mf4DO/Y6smAiGyVQi4u4IOdBLTQIeMnf2YGF5bUvoickgokBa3nZkA7rO5aqZ1l4eK8gsWrVATzGPE4k2oZbTDdMGLFTAe+klFYe6r8zrbvLGqTgO4WxTklkESn9ESHvb/1nLRefJnI51dPAR+nn3l38vcncmbEmLjzxp0seavGW0ABMXgW/GRNtufsMqesXU6rJj2sbDM3V11QU2BIaQzGIka8qRh/Npgvu4EiZXLqgPj8d0pnC3fp3Vn3Ig4leiosczaATVLMxc=
    - secure: 
        BChBEtSrW2B5azq64lw17vipz1Wi16C/pPLIcGpqrv24kN5g7gdGjJztkefHkPwHfSuwZ/CUqc0FMEUnKiwlX0+OedgjCRawKnE/mxOXkOyC7XHwGS93vVFHD6pp9ajXGXVq62fkjWmakLVap9gmDI/xuVkCVrAa8U7gHKpRy2xbCdkhMGsYBA6J24Yq4wxarLpltyg38l/Nmrp1fVNJwiMtRzkf6vglTxebI0HySnvJJqENK2QSFl8h1nIBQrZTR28GYICZuEAvRrRZt0BbB4MaaysvGJJNdn5FD+ielzvgj7BzsOjOCcEcBfrE+Rqms/1KsCJD1r+qWQ82irR5WHJBaNL+P5L7JEKrKnTeR/JmHf+Fu7riwvUEoGfQeX1szOD6iONvu+6Z3MYiJ8ID6eaorR+PEerd4nYmHJfBC6HZJWEHj+Ztr5RFsFZTG4kJRHyVZgPIZN47w8IXy4rZsVO9BUEpDtCqaH+qvvjVua09+8zxC6H7NvuPAvqKOPzu1YTVYuf34SYS/VzY+WHUvgL2oQ/zGRhKKNzdxttsN0phyVR2xyrOaW/Eh9l4UhWIl7PyE82lgGs/03Y0j8o3zbH5r97CjFLYPYpn17DJKh1mxyUMRG4hdXoE0hMCVdVNj7nniil3YAz12+4jAiLDqlDp6fyh64IJYgiKF4fMv3A=
    - secure: 
        koBRwpngUXvZB1zj7VV72i4DVXJBzgAdWXAyTEAvHpn9Zfk9ddyvu+xeIrevr/0wan6bGxpuPCEfZnkSnGejmjANA6I+dvU98FIBLxrY6okgpIzhYltj9y2e0NhxkjulaQPzlrz0mBtzFdSj1rbvaY4cMdCh+IQsOmmoCdE2GgrNmV5/V21XWY3m8azQuBC9Q8RmTafsKbNahdlYFLrVMz7W2eWWHoDysgPElvWqlXKmeKhDBJOU/aNy4vciNsSEU66TeWKWbl3Wvea+OPgpMr7JvoGWiOohJe9PiOAp0YU3Kv68j8V6Sugh+wSplqjVeKd855w8Yo5gh7FjRiX9MwPidAa+3XmW4sLVCOcRyAknvy9IGjTxb7HdKLMNj/wbdyYIWKGP+ZwM7tIxCY7FlXWIL1crRhMU38ph+gwJs2ws40jkXXBqdqTUicrhtD44PwOi5lWbGHf2EPF7abjOJKMo6TgPP+lnSMQeYolQM+p1vplySfezJ/sisp7fhXMThjgxV6VTZIFRw4ZX6g0K/5Z+v5WY041njAMe5Qits/r3ND10tp47du9M1/rLbFKAuCqtODrQXaeuOJIFCCtYSY8koEpdaIAbSoqct+DsRGylNPiDEzt/g3QgCfT/UGk+CbOxGrEWWVll+j/clwnLFA9TqSjXqmlJWnpAHGiwffY=
notifications:
  slack:
    secure: 
      HEEJwMlmaJJ23g2FsofTyEucsvBZxblUoC2lg2hTd/4QKKCudvYH9zCyCl2tw2qiJZt9iFoiXux3Ote9XtNQrh44Rl8xXELIH/JQKT0O3FQr+L82la0+tZb9eDXZkFekHho1zwBYaN2/3YOYZmiIIk8/yCWuyGp4MaZIaZon+atUV2mGyG0KwQJNoAiTAKxOFKFeyHFzYToMTdTecVRAInRIWgEx1amimYe95spANOc+xbuaCfCKbPqWgjhe1z8T8DNDkmL/1cdntokCJdfe0O20eICAUxC7tS9aLxekcZAU6T0z7yeUjJaP/vKJLpE/GnDDHBG+G8oJbEJkDxtZBHwBSCP1pEWFDVCZhDoDNKFNImw5WVBfTni4QNeaei1i3gBkOOvKS4IH4lWmASECxICyCpIuzlQ8ZXJiSAkTdoFydNg3qikq3x4oNNX5BHRK8WhMQFaL36NUAMcYknLz34q8G4lrcx828ZBmQbzevGhN5of7lz1u6u7oUzs33oXEubjaraiHw39EOUoCM9wrfatCGzOW/2mdpQ60wPyIqj9HySUvYfbITHgklJhBwPuAkKE4JwfQc8Ge51WLy9i++0V1XYDh11EeEsir6Gc07W8XYPmoU63VxpRYY7fWgvsTdWE7OoZc5ses8Eh36r4pKcju3AAkLjrVNIKTDtFa6E0=
