adtechmedia.settings:
  type: config_object
  label: AdTechMedia settings
  mapping:
    api_key:
      type: string
      label: 'API key'
    api_value:
      type: string
      label: 'API value'
    country:
      type: string
      label: Country
    revenue_model:
      type: string
      label: 'Revenue Model'
    content_preview:
      type: string
      label: 'Content Preview'
    locking_algorithm:
      type: string
      label: 'Locking Algorithm'
    content_pricing:
      type: string
      label: 'Content Pricing'
    content_currency:
      type: string
      label: 'Content Currency'
    content_paywall:
      type: string
      label: 'Content Paywall'
    dns_access:
      type: string
      label: 'DNS Access'
    email:
      label: Email
      type: string
    pledge_view:
      label: 'Pledge View'
      type: string
    confirm_view:
      label: 'Confirm View'
      type: string
    refund_view:
      label: 'Refund View'
      type: string
    pay_view:
      label: 'Pay View'
      type: string
    login_view:
      label: 'Login View'
      type: string
